name: Qt5CMakeTemplate

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '${{ github.repository }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-20.04]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.7.0

    - name: Build
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install" -B build
        cmake --build build
        cmake --install build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Qt5CMakeTemplate-${{ matrix.os }}
        path: install